import type { Metadata } from 'next';
import { Josefin_Sans } from 'next/font/google';
import './globals.css';
import { cn } from '@/utils/cn';

const JosefineSans = Josefin_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Todo app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          JosefineSans.className,
          'bg-background text-foreground dark'
        )}
      >
        {children}
      </body>
    </html>
  );
}
